# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-11 11:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20180105_0508'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_opeartion', '0002_auto_20171222_1012'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfav',
            unique_together=set([('user', 'goods')]),
        ),
    ]
