# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_opeartion', '0003_auto_20180111_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userleavingmessage',
            name='file',
            field=models.FileField(help_text='上传的文件', upload_to='message/image/', verbose_name='上传的文件'),
        ),
    ]
